server:
  port:
    9090

logging:
  level:
    com.solvd.micro: DEBUG
  file:
    name: ticket-service.log
    path: /

spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: mongodb://${MONGODB_DOMAIN}:27017/tickets
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_DOMAIN}:5432/postgres?currentSchema=tickets
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver: org.postgresql.Driver
  jackson:
    default-property-inclusion: non_null
  application:
    name: TICKET-SERVICE
  kafka:
    topic: users
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}:9092
    properties:
      spring:
        json:
          trusted:
            packages: com.solvd.micro9.tickets.web.dto
    consumer:
      group-id: userGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer