apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets-app
          image: eyakauleva/ticket-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: MONGODB_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: tickets-configmap
                  key: MONGODB_DOMAIN
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets-tickets
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets-tickets
                  key: MONGODB_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: tickets-configmap
                  key: KAFKA_BOOTSTRAP_SERVERS