apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-stateful-tickets
spec:
  serviceName: pg-service-tickets
  replicas: 1
  selector:
    matchLabels:
      app: postgres-tickets
  template:
    metadata:
      labels:
        app: postgres-tickets
    spec:
      containers:
        - name: tickets-service-postgres
          image: postgres:14.6-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secrets-tickets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets-tickets
                  key: POSTGRES_PASSWORD
      volumes:
        - name: tickets-service-db
          hostPath:
            path: /data
  volumeClaimTemplates:
    - metadata:
        name: tickets-service-db
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi

